SELECT
a.conn_id as KEY_CODE
, c.stt_result_detail_id as KEY_ID
, c.sentence as KEY_SENTENCE
, a.xcompany as XCOMPANY
, 'CALL' as CHANNEL
, a.conn_id as OBJECT_ID
, ''  as TA_MODEL_ID
, ''  as CATEGORY1
, ''  as CATEGORY2
, '' as CATEGORY3
, '' as CATEGORY4
, '' as CATEGORY5
, c.sentence_id  as SENTENCE_ID
, NULL  as SEQ
,''  as TA_MODEL_ID_VERSION
, a.company as COMPANY
, '' as DETECT_ALGORITHM
, a.start_dttm as OBJECT_ID_START_DTTM
, '' as CATEGORY
, c.speaker_code as SIDE
, NULL as TA_COMPLETE_DATE
, NULL as TA_COMPLETE_TIME
, c.start_time as TS
, c.end_time as TE
, NULL as INTENTION
, c.sentence as SENTENCE
, NULL as ACCURACY
, NULL as ACCURACY_BY_WORD
, NULL as ACCURACY_BY_WORD_TOP1
, NULL as DETECT_KEYWORD
, NULL as DETECT_PATTERN
, NULL as TA_COMPLETE_DTTM
, NULL as CREATE_DTTM
, a.mon as MON
, NULL as REVIEW_CD
, NULL as REVIEW_NOTES
, NULL as REVIEW_USER_ID
, NULL as REVIEW_DTTM
, NULL as C_DTTM
, a.last_ticket_no as LAST_TICKET_NO
, a.guid as GUID
, a.process_type as PROCESS_TYPE
, a.customer as CUSTOMER
, a.status as  STATUS
, a.recipient as  RECIPIENT
, a.employee as EMPLOYEE
, a.employee_g as EMPLOYEE_G
, a.detail_type  as DETAIL_TYPE
, a.service_type as SERVICE_TYPE
, a.posting_Date as POSTING_DATE
, a.cic_prd as CIC_PRD
, a.cic_sub_prd as CIC_SUB_PRD
, a.svc_prd as SVC_PRD
, a.svc_prd2 as SVC_PRD2
, a.model as MODEL
, a.serial_no as SERIAL_NO
, a.imei as IMEI
, a.category1 as TICKET_CATEGORY1
, a.category2 as TICKET_CATEGORY2
, a.symptom_cat1 as SYMPTOM_CAT1
, a.symptom_cat2 as  SYMPTOM_CAT2
, a.symptom_cat3 as SYMPTOM_CAT3
, a.asc_code as  ASC_CODE
, a.inoutwty as INOUTWTY
, a.ernam as  TICKET_ERNAM
, a.callani as CALLANI
, a.calldnis as CALL_DNIS
, a.calltype as CALL_TYPE
, a.tenant_id as TENANT_ID
, a.agent_id as  AGENT_ID
, a.skill_id as  SKILL_ID
, a.site_id as SITE_ID
, a.skill_category as SKILL_CATEGORY
, a.skill_ccgroup as SKILL_CCGROUP
, a.skill_lob as  SKILL_LOB
, a.end_dttm as OBJECT_ID_END_DTTM
, a.call_length as OBJECT_ID_LENGTH
, a.agent_transfer_dttm as  AGENT_TRANSFER_DTTM
, a.parent_callid as  PARENT_CALLID
, a.doc_dt as DOC_DT
from SIRV.m_call  as a,
BIZ.stt_result_tb  as b ,
BIZ.stt_result_detail_tb as c
where a.conn_id = b.ticket_id limit 100;
